MySpace/MySpace/urls.py
import xadmin

from .rss import LastesPostFeed

from .autocomplete import TagAutoComplete, CategoryAutoComplete, ProvinceComplete
from django.contrib.sitemaps import views as sitemap_views
from django.urls import path, include, re_path
from django.views.static import serve

from MySpace import settings
from apps.home.views import HomeView
from .sitemap import ArticleSitemap


urlpatterns = [
    path('admin/', xadmin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

    path('home/', include(('apps.home.urls', 'home'), namespace='home')),
    path('picture/', include(('apps.picture.urls', 'picture'), namespace='picture')),
    path('life/', include(('apps.life.urls', 'life'), namespace='life')),
    path('article/', include(('apps.article.urls', 'article'), namespace='article')),
    path('travel/', include(('apps.travel.urls', 'travel'), namespace='travel')),
    path('comment/', include(('apps.comment.urls', 'comment'), namespace='comment')),
    path('mdeditor/', include(('mdeditor.urls', 'mdeditor'), namespace='mdeditor')),

    path('category-autocomplete/', CategoryAutoComplete.as_view(), name='category-autocomplete'),
    path('tag-autocomplete/', TagAutoComplete.as_view(), name='tag-autocomplete'),
    path('province-autocomplete/', ProvinceComplete.as_view(), name='province-autocomplete'),

    path('', HomeView.as_view(), name='home'),
    path('rss', LastesPostFeed(), name='rss'),
    path('sitemap.xml', sitemap_views.sitemap, {'sitemaps': {'articles': ArticleSitemap}}),

]

MySpace/apps/article/urls.py
#!usr/bin/env python3
# -*- coding: utf-8 -*-
__author__ = "Monkey"


from django.urls import path
from .views import ArticleListView, ArticleDetailView, CategoryListView, TagListView, ArchiveListView

urlpatterns = [
    path('', ArticleListView.as_view(), name="article"),
    path('<int:id>/', ArticleDetailView.as_view(), name="detail"),
    path('tag/<int:id>', TagListView.as_view(), name="tag"),
    path('category/<int:id>', CategoryListView.as_view(), name="category"),
    path('archive/<int:year>/<int:month>', ArchiveListView.as_view(), name="archive"),

]

MySpace/apps/article/models.py
from django.db import models
from django.db.models import QuerySet
from django.utils.safestring import mark_safe

import mistune
from mdeditor.fields import MDTextField
from ..utils.basemodel import VisitBaseModel, BaseModel


class Category(BaseModel):

    name = models.CharField(max_length=50, verbose_name="名称")

    def flush_cache_keys(self) -> dict:

        self.CACHE_DICT['keys'] = {
            f'context:{self._meta.app_label}:article:list:by:{self._meta.model_name}:{self.id}',  # 按分类划分的文章列表
            f'context:{self._meta.app_label}:{self._meta.model_name}:list'   # 分类列表
        }
        return self.CACHE_DICT

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = verbose_name_plural = "分类"
        # ordering = ['-id', ]


class Tag(BaseModel):

    name = models.CharField(max_length=10, verbose_name="名称")

    def flush_cache_keys(self) -> dict:
        self.CACHE_DICT['keys'] = {
            f'context:{self._meta.app_label}:article:list:by:{self._meta.model_name}:{self.id}',   # 按标签划分的文章列表
            f'context:{self._meta.app_label}:{self._meta.model_name}:list'   # 标签列表
        }
        return self.CACHE_DICT

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = verbose_name_plural = "标签"
        ordering = ['-id', ]


class Article(VisitBaseModel):

    title = models.CharField(max_length=255, verbose_name="标题")
    desc = models.CharField(max_length=512, verbose_name='摘要')
    content = MDTextField(verbose_name="正文", help_text="MarkDown格式")
    content_html = models.TextField(verbose_name="正文html", blank=True, editable=False)
    category = models.ForeignKey(Category, verbose_name="文章分类", on_delete=models.DO_NOTHING)
    tag = models.ManyToManyField(Tag, verbose_name='标签')

    def flush_cache_keys(self) -> dict:

        self.CACHE_DICT['keys'] = {
            f'context:{self._meta.app_label}:{self._meta.model_name}:list',  # 文章列表缓存
            f'context:{self._meta.app_label}:{self._meta.model_name}:list:by:category:{self.category_id}',  # 关联的分类
            f'context:{self._meta.app_label}:{self._meta.model_name}:detail:{self.id}',  # 文章详情
            f'context:{self._meta.app_label}:{self._meta.model_name}:new',   # 最新文章
            f'context:{self._meta.app_label}:{self._meta.model_name}:hot',   # 最热文章
        }

        self.CACHE_DICT['match'] = {f'context:{self._meta.app_label}:{self._meta.model_name}:list:by:tag:*'}   # 所有按标签分类文章列表

        return self.CACHE_DICT

    def save(self, *args, **kwargs) -> None:
        """ 重写文章主体 """
        safe_content = mark_safe(self.content)
        self.content_html = mistune.markdown(safe_content)
        super(Article, self).save(*args, **kwargs)

    @classmethod
    def query_hot_article(cls, count: int = 6, *args, **kwargs) -> QuerySet:
        """
        最热文章
        @return:
        """
        fields: tuple = ('id', 'title', 'visit')
        query: QuerySet = cls.objects.values(*fields).order_by('-visit')[:count]
        return query

    @classmethod
    def query_new_article(cls, count: int = 6, *args, **kwargs) -> QuerySet:
        """
        最新文章
        @return:
        """
        fields: tuple = ('id', 'title')
        query: QuerySet = cls.objects.values(*fields).order_by('-id')[:count]
        return query

    @classmethod
    def query_recommend_article(cls, count: int = 6, *args, **kwargs) -> QuerySet:
        """
        相似度推荐
        @return:
        """

    class Meta:
        verbose_name = verbose_name_plural = "文章"

    def __str__(self):
        return self.title

MySpace/apps/article/views.py
import datetime

from django.db.models import QuerySet
from django.views.generic.base import View
from django.views.generic.list import ListView

from .models import Article
from ..comment.models import ArticleComment
from ..utils.mixin import NavViewMixin, VisitIncrMixin, rich_render
from ..utils.tools import proxy_query


class ArticleView(NavViewMixin, ListView):
    """ 抽象类 """
    paginate_by = 10

    allow_empty = True

    context_object_name: str = "article_list"

    template_name: str = "article_list.html"

    model: 'model.Model' = Article

    fields: tuple = (
        'id', 'title', 'desc', 'create_time', 'visit', 'category__name'
    )

    def get_queryset(self, *args, **kwargs) -> QuerySet:
        """ 获取 status = status.NORMAL 的文章查询集 """

        # 过滤 status=STATUS_NORMAL的文章
        qs: QuerySet = self.model.objects.filter()

        # 看是否有其他过滤条件，过滤查询集合
        query_filter: dict = kwargs.get('query_filter')
        # 看是否有自定义的查询字段
        fields: tuple = kwargs.get('fields')

        order_by = kwargs.get('order') or '-id'

        if isinstance(query_filter, dict):
            qs = qs.filter(**query_filter)

        fields: tuple = fields or self.fields

        # 一次SQL查询完所有值, 防止在模版中遍历 执行n次 SQL查询
        return qs.values(*fields).order_by(order_by)


class ArticleListView(ArticleView):
    """ 文章列表试图 """

    def get_queryset(self, *args, **kwargs) -> QuerySet:

        # 缓存键
        cache_key: str = f'context:{self.model._meta.app_label}:{self.model._meta.model_name}:list'
        func = super(ArticleListView, self).get_queryset
        return proxy_query(key=cache_key, func=func, timeout=3600)


class CategoryListView(ArticleView):
    """ Category of articles by tag. """

    def get_queryset(self) -> QuerySet:

        category_id: int = self.kwargs.get('id')
        cache_key: str = f'context:{self.model._meta.app_label}:{self.model._meta.model_name}:list:by:category:{category_id}'
        query_filter: dict = {'category': category_id}
        func = super(CategoryListView, self).get_queryset

        return proxy_query(key=cache_key, func=func, query_filter=query_filter)


class TagListView(ArticleView):
    """ 这与 category 的list 视图 几乎一摸一样，但是还是不抽取公共代码的好～  """

    def get_queryset(self) -> QuerySet:

        tag_id: int = self.kwargs.get('id')
        cache_key: str = f'context:{self.model._meta.app_label}:{self.model._meta.model_name}:list:by:tag:{tag_id}'
        query_filter: dict = {'tag': tag_id}
        func = super(TagListView, self).get_queryset

        return proxy_query(key=cache_key, func=func, query_filter=query_filter)


class ArchiveListView(ArticleView):
    """  List of articles by create time. """

    def get_queryset(self) -> QuerySet:

        year: int = self.kwargs.get('year', 2019)
        month: int = self.kwargs.get('month', 0)

        # 获取归档日期区间
        if 0 < month < 13:
            days: int = (datetime.datetime(year, month + 1, 1) - datetime.datetime(year, month, 1)).days
            start: datetime.date = datetime.date(year, month, 1)
            end: datetime.date = datetime.date(year, month, days)
        else:
            start: datetime.date = datetime.date(year, 1, 1)
            end: datetime.date = datetime.date(year, 12, 31)
        # 拼接cache键
        cache_key: str = f'{start}-{end}'
        func = super(ArchiveListView, self).get_queryset
        query_filter: dict = {'create_time__range': (start, end)}  # 过滤条件

        return proxy_query(key=cache_key, func=func, query_filter=query_filter)


class ArticleDetailView(VisitIncrMixin, View):
    """ 文章详情视图 """
    template_name = 'article_detail.html'
    model = Article

    def get(self, request, *args, **kwargs) -> 'HttpResponse':

        article_id = self._pk = kwargs.get('id')
        # 获取文章详情和标签信息
        cache_key: str = f'context:{self.model._meta.app_label}:{self.model._meta.model_name}:detail:{article_id}'
        context: dict = proxy_query(key=cache_key, func=self.query_article, article_id=article_id)

        # 获取文章评论（因为评论信息改动较为频繁，且需要尽可能快的更新，so 单独缓存）
        cache_key: str = f'context:{self.model._meta.app_label}:{self.model._meta.model_name}:comment:{article_id}'
        comment_qs: list = proxy_query(key=cache_key, func=self.query_comment, article_id=article_id)

        # 最热文章
        cache_key: str = f'context:{self.model._meta.app_label}:{self.model._meta.model_name}:hot'
        article_hot: QuerySet = proxy_query(key=cache_key, func=self.model.query_hot_article, count=10)

        # 最新文章
        cache_key: str = f'context:{self.model._meta.app_label}:{self.model._meta.model_name}:new'
        article_new: QuerySet = proxy_query(key=cache_key, func=self.model.query_new_article, count=10)

        # 相关推荐

        # 拼接上下文
        context.update({'comment_list': comment_qs})   # 评论列表
        context.update({'article_hot': article_hot})   # 最热文章
        context.update({'article_new': article_new})   # 最新文章


        # 添加浏览
        response = rich_render(request, 'article_detail.html', context=context, *args, **kwargs)
        self.handle_visited(request, *args, **kwargs)   # 增加访问
        return response

    def query_article(self, article_id, *args, **kwargs) -> dict:
        """
        查询文章详情
        @param article_id:  文章ID
        @return: QuerySet 文章详情 带文章标签
        """
        fields: tuple = (
            'id', 'title', 'content_html', 'create_time', 'visit', 'content_html',
            'category__id', 'category__name', 'tag__id', 'tag__name',
        )

        if hasattr(self, '_pk'):
            article_id: int = getattr(self, '_pk')

        query: QuerySet = Article.objects.filter(id=article_id).prefetch_related('tag').select_related('category').values(*fields)
        article: dict = dict()
        tag_list: list = list()
        for record in query.iterator():
            if not article:
                article = record
            tag_list.append({'id': record.get('tag__id'), 'name': record.get('tag__name')})

        return {'article': article, 'tags': tag_list}

    def query_comment(self, article_id, *args, **kwargs) -> QuerySet:
        """
        查询评论
        @param article_id: 文章ID  type:int
        @return: 可见评论查询集  type: QuerySet
        """
        fields: tuple = ('id', 'create_time', 'context')
        if hasattr(self, '_pk'):
            article_id: int = getattr(self, '_pk')

        query: QuerySet = ArticleComment.objects.filter(article_id=article_id).values(*fields)
        return query

    # @staticmethod
    # def query_hot_article() -> QuerySet:
    #     """
    #     最热文章
    #     @return:
    #     """
    #     fields: tuple = ('id', 'title', 'visit')
    #     query: QuerySet = Article.objects.values(*fields).order_by('-visit')[:10]
    #     return query
    #
    # @staticmethod
    # def query_new_article() -> QuerySet:
    #     """
    #     最新文章
    #     @return:
    #     """
    #     fields: tuple = ('id', 'title')
    #     query: QuerySet = Article.objects.values(*fields).order_by('-id')[:10]
    #     return query

    # @staticmethod
    # def query_top_article() -> QuerySet:
    #     """
    #     置顶
    #     @return:
    #     """
    #
    # def query_recommend_article(self) -> QuerySet:
    #     """
    #     相似度推荐
    #     @return:
    #     """

MySpace/apps/article/templates/article_base.html
{% extends 'base.html' %}


{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static '/css/article.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">

    {% block article-css %}

    {% endblock %}
{% endblock %}

{% block main %}
    <div id="container" class="clearfix">

        <div id="main-left" class="float-l">
            {% block main-left %}

            {% endblock %}

        </div>

        <div id="main-center" class="float-l">
            {% block main-center %}

            {% endblock %}

        </div>

        <div id="main-right" class="float-r">
            {% block main-right %}

            {% endblock %}

        </div>

    </div>

    <div id="page">
        {% if page_obj %}
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
            {% endif %}

            第{{ page_obj.number }}页 共{{ paginator.num_pages }}页

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
            {% endif %}
        {% endif %}
    </div>


{% endblock %}

{% block js %}
    {% block article-js %}

    {% endblock %}
{% endblock %}

MySpace/apps/article/templates/article_detail.html
{% extends 'article_base.html' %}


{% block title %}
    详情页:{{ article.title }}
{% endblock %}


{% load static %}

{% block article-css %}
    <link rel="stylesheet" href="{% static 'css/googlecode.css' %}">
{% endblock %}

{% load static %}

{% block main-left %}
    <!-- 边栏数据 -->
    <div id="leftSideBar">

        <div id="sidebar_tag" class="left_side_block">
            <p class="rlt-head"> 分类标签 <i class="fa fa-minus" aria-hidden="true"></i></p>
            <ul class="rlt-body">
                {% for tag in tag_list %}
                    <li><i class="fa fa-paperclip" aria-hidden="true"></i> <a
                            href='{% url 'article:tag' tag.id %}'>{{ tag.name }}</a></li>
                {% endfor %}
            </ul>
        </div>

        <div id="sidebar_category" class="left_side_block">
            <p class="rlt-head"> 文章分类 <i class="fa fa-minus" aria-hidden="true"></i></p>
            <ul class="rlt-body">
                {% for category in category_list %}
                    <li><i class="fa fa-tags" aria-hidden="true"></i> <a
                            href='{% url 'article:category' category.id %}'>{{ category.name }}</a></li>
                {% endfor %}
            </ul>

        </div>

        <div id="sidebar_hot" class="left_side_block">
            <p class="rlt-head"> 最热文章 <i class="fa fa-minus" aria-hidden="true"></i></p>
            <ul class="rlt-body">
                {% for article in article_hot %}
                    <li><a href="{% url "article:detail" article.id %}">{{ article.title }}</a></li>
                {% endfor %}

            </ul>
        </div>

        <div id="sidebar_new" class="left_side_block">
            <p class="rlt-head"> 最新推荐 <i class="fa fa-chevron-down" aria-hidden="true"></i></p>
            <ul class="rlt-body" hidden>
                {% for article in article_new %}
                    <li><a href="{% url "article:detail" article.id %}">{{ article.title }}</a></li>
                {% endfor %}

            </ul>
        </div>

        <div id="sidebar_archive" class="left_side_block">
            <p class="rlt-head"> 文章归档 <i class="fa fa-chevron-down" aria-hidden="true"></i></p>
            <ul class="rlt-body" hidden>
                {% for year, months in date_merge.items %}

                    <li class='has-sub'><a href="{% url 'article:archive' year 0 %}">{{ year }}年</a>
                        <ul>
                            {% for month in months %}
                                <li><a href="{% url 'article:archive' year month %}">{{ month }} 月</a></li>
                            {% endfor %}
                        </ul>
                    </li>



                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

{% block main-center %}
    <!-- 附加数据 -->
    <div id="page_data" data-article_id="{{ article.id }}"></div>
    {% csrf_token %}
    <div id="article-detail">
        <div id="article-title">
            {{ article.title }}
        </div>
        <div id="article-decoration">
            <div id="cookies">
                <span class="tip c-black b-white">原创</span>
                <span class="tip c-black b-white">分类</span>
                <span class="tip b-error c-white"><a
                        href="{% url 'article:category' article.category__id %}">{{ article.category__name }}</a></span>
                <span class="tip c-black b-white">发布</span><span
                    class="tip b-info c-white">{{ article.create_time }}</span>
                <span class="tip c-black b-white">阅读</span><span
                    class="tip b-warning c-white">{{ article.visit }}</span>
            </div>
            <div id="tag" class="float-r">
                <span class="tip b-info">Tags</span> <i></i>
                {% for tag in tags %}
                    <span class="tag-elem"><a href="{% url 'article:tag' tag.id %}">{{ tag.name }}</a></span> <i></i>
                {% endfor %}
            </div>
        </div>
        <div id="article-text" class="para">
            {{ article.content_html | safe }}
        </div>
    </div>
    <div id="new_comment">


        <textarea name="comment" id="comment-text" maxlength="256" placeholder="@评论："></textarea>
        <p id="add_cmt_bar">
            <span id="post-btn"><i class="fa fa-paper-plane" aria-hidden="true"></i> 发表</span>
            <span>word</span>:<span id="num-word"></span>
        </p>
    </div>

    <div id="comment">
        {% for comment in comment_list %}
            <div class="cmt_line">
                <div class="cmt_avatar">
                    <img src="{% static 'img/AVATAR.png' %}" alt="">
                </div>
                <div class="cmt_right">
                    <div class="cmt_text">{{ comment.context | truncatechars:326 }}</div>
                </div>
                <div class="cmt_footer">
                    <span hidden>{{ comment.id }}</span>
                    <span class="cmt_time"><i class="fa fa-clock-o"
                                              aria-hidden="true"></i> {{ comment.create_time }}</span>
                    <span></span>
                </div>
            </div>
        {% empty %}

        {% endfor %}
    </div>

{% endblock %}

{% block main-right %}
    <!-- 边栏数据 -->
    <div id="contentSidebar">
        <p id="ctt-head"> CONTENTS<i class="fa fa-times" aria-hidden="true"></i></p>
        <div id="ctt-body"></div>
    </div>

    <div id="bottom-tool">
        <div id="toTop"><i class="fa fa-arrow-up" aria-hidden="true"></i></div>
        <div id="showContent"><i class="fa fa-list" aria-hidden="true"></i></div>
        <div id="sendEmail"><a href="mailto:931976722@qq.com"><i class="fa fa-envelope-o" aria-hidden="true"></i></a>
        </div>
    </div>
{% endblock %}

{% block article-js %}
    <script src="{% static 'js/highlight.min.js' %}"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script src="{% static 'js/detail.js' %}"></script>
{% endblock %}

MySpace/apps/article/templates/article_list.html
{% extends 'article_base.html' %}

{% block title %}
    博客列表页
{% endblock %}

{% block article-css %}

{% endblock %}

{% block main-center %}

    <div id="article-list">

        <div id="day-cookie">Cookie:<span>专注是一种习惯！</span></div>

        {% for article in article_list %}

            <div class="article clearfix">

                <div class="title">
                    <a href="{% url "article:detail" article.id %}">{{ article.title }}</a>
                </div>

                <div class="summary para">

                    <span>摘要:</span>
                    {{ article.desc | truncatechars:120 }}
                </div>

                <div class="footer float-r">

                    <span class="head-tip"><i class="fa fa-user" aria-hidden="true"></i> 作者</span><span class="author end-tip">Clark Monkey</span>
                    <span class="head-tip"><i class="fa fa-paper-plane" aria-hidden="true"></i> 发布于</span><span class="release end-tip">{{ article.create_time }}</span>
                    <span class="head-tip"><i class="fa fa-tags" aria-hidden="true"></i> 分类</span><span class="category end-tip">{{ article.category__name }}</span>
                    <span class="head-tip"><i class="fa fa-eye" aria-hidden="true"></i> 阅览</span><span class="category end-tip">{{ article.visit }}</span>

                </div>


            </div>

        {% empty %}
            <div class="article">
                <p class="title">
                    空空如也！
                </p>
            </div>

        {% endfor %}

    </div>

{% endblock %}


{% block article-js %}

{% endblock %}