MySpace/MySpace/urls.py
import xadmin

from .rss import LastesPostFeed

from .autocomplete import TagAutoComplete, CategoryAutoComplete, ProvinceComplete
from django.contrib.sitemaps import views as sitemap_views
from django.urls import path, include, re_path
from django.views.static import serve

from MySpace import settings
from apps.home.views import HomeView
from .sitemap import ArticleSitemap


urlpatterns = [
    path('admin/', xadmin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

    path('home/', include(('apps.home.urls', 'home'), namespace='home')),
    path('picture/', include(('apps.picture.urls', 'picture'), namespace='picture')),
    path('life/', include(('apps.life.urls', 'life'), namespace='life')),
    path('article/', include(('apps.article.urls', 'article'), namespace='article')),
    path('travel/', include(('apps.travel.urls', 'travel'), namespace='travel')),
    path('comment/', include(('apps.comment.urls', 'comment'), namespace='comment')),
    path('mdeditor/', include(('mdeditor.urls', 'mdeditor'), namespace='mdeditor')),

    path('category-autocomplete/', CategoryAutoComplete.as_view(), name='category-autocomplete'),
    path('tag-autocomplete/', TagAutoComplete.as_view(), name='tag-autocomplete'),
    path('province-autocomplete/', ProvinceComplete.as_view(), name='province-autocomplete'),

    path('', HomeView.as_view(), name='home'),
    path('rss', LastesPostFeed(), name='rss'),
    path('sitemap.xml', sitemap_views.sitemap, {'sitemaps': {'articles': ArticleSitemap}}),

]

MySpace/apps/article/urls.py
#!usr/bin/env python3
# -*- coding: utf-8 -*-
__author__ = "Monkey"


from django.urls import path
from .views import ArticleListView, ArticleDetailView, CategoryListView, TagListView, ArchiveListView

urlpatterns = [
    path('', ArticleListView.as_view(), name="article"),
    path('<int:id>/', ArticleDetailView.as_view(), name="detail"),
    path('tag/<int:id>', TagListView.as_view(), name="tag"),
    path('category/<int:id>', CategoryListView.as_view(), name="category"),
    path('archive/<int:year>/<int:month>', ArchiveListView.as_view(), name="archive"),

]

MySpace/apps/home/urls.py
#!usr/bin/env python3
# -*- coding: utf-8 -*-
__author__ = "Monkey"


from django.urls import path
from .views import *

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('me', AboutMe.as_view(), name='me'),
    path('search', AllSiteSearch.as_view(), name='search'),
]

MySpace/apps/life/urls.py
#!usr/bin/env python3
# -*- coding: utf-8 -*-
__author__ = "Monkey"


from django.urls import path
from .views import LifeView, CookingView, BookView, NoteView, PerceptionView

urlpatterns = [
    path('', LifeView.as_view(), name='life'),
    path('cooking/', CookingView.as_view(), name='cook_list'),
    path('book/', BookView.as_view(), name='book_list'),
    path('note/', NoteView.as_view(), name='note_list'),
    path('perception/', PerceptionView.as_view(), name='perception_list'),

    path('cooking/<int:id>', CookingView.as_view(), name='cook'),
    path('book/<int:id>', BookView.as_view(), name='book'),
    path('note/<int:id>', NoteView.as_view(), name='note'),
    path('perception/<int:id>', PerceptionView.as_view(), name='perception'),
]

MySpace/apps/picture/urls.py
#!usr/bin/env python3
# -*- coding: utf-8 -*-
__author__ = "Monkey"


from django.urls import path
from .views import AlbumListView, ImageView, AlbumDetailView

urlpatterns = [
    path('', AlbumListView.as_view(), name='album'),
    path('album/<int:id>/', AlbumDetailView.as_view(), name='album_detail'),
    path('album/<int:album_id>/image/<int:image_id>/', ImageView.as_view(), name='image_detail'),
]

MySpace/apps/travel/urls.py
#!usr/bin/env python3
# -*- coding: utf-8 -*-
__author__ = "Monkey"

import xadmin
from django.urls import path
from .views import TravelView

urlpatterns = [
    path('admin/', xadmin.site.urls),
    path('', TravelView.as_view(), name='travel'),
    path('province/<int:id>', TravelView.as_view(), name='province'),
    path('province/<int:p_id>/city/<int:c_id>', TravelView.as_view(), name='city'),
]

MySpace/apps/home/models.py
from django.db import models

# Create your models here.

MySpace/apps/home/views.py
from django.db.models import QuerySet
from django.views.generic import View
from ..utils.mixin import rich_render, CacheMixin
from ..utils.tools import proxy_query
from ..article.models import Article
from ..picture.models import Album

# Create your views here.


# 首页缓整个页面
class HomeView(CacheMixin, View):

    cache_timeout: int = 5 * 60  # 首页缓存时间
    article_count: int = 6   # 首页展示文章个数
    album_count: int = 8   # 首页展示相册个数

    def get(self, request, *args, **kwargs):

        context: dict = dict()  # 初始化页面上下文
        context.update(self.query_article())   # 更新文章页上下文数据
        context.update(self.query_album())   # 更新相册上下文数据
        # context.update(self.query_life())    # 更新 生活上下文数据
        # context.update(self.query_travel())    # 更新足迹上下文数据

        return rich_render(request, 'home.html', context=context)

    def query_article(self) -> dict:
        """ 获取最新最热文章 """
        article_count = 10
        if hasattr(self, 'article_count'):
            article_count = self.article_count

        cache_key: str = f'context:{Article._meta.app_label}:{Article._meta.model_name}:hot'
        article_hot: QuerySet = proxy_query(key=cache_key, func=Article.query_hot_article, count=10)[:article_count]

        cache_key: str = f'context:{Article._meta.app_label}:{Article._meta.model_name}:new'
        article_new: QuerySet = proxy_query(key=cache_key, func=Article.query_new_article, count=10)[:article_count]

        context: dict = {
            'article_hot': article_hot,
            'article_new': article_new,
            # 'tags_list': tag_list,     rich_render 会填充 tag_list 字段到上下文
        }

        return context

    def query_album(self) -> dict:
        """ 获取相册 """
        cache_key: str = f'context:home:album:list'

        album_count: int = 8
        if hasattr(self, 'album_count'):
            album_count = self.album_count

        def inner_query(count, *args, **kwargs) -> QuerySet:
            fields: tuple = ('id', 'cover',)
            return Album.objects.values(*fields)[:count]

        album_list: QuerySet = proxy_query(key=cache_key, func=inner_query, count=album_count)

        return {'album_list': album_list}

    def query_life(self) -> dict:
        """  """

    def query_travel(self) -> dict:
        """ 旅程列表 """


class AboutMe(View):

    def get(self, request, *args, **kwargs):
        return rich_render(request, 'me.html')


class AllSiteSearch(View):
    """
    分apps 展示内容 提供连接
    """

MySpace/apps/home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>

    {% load static %}

    <link rel="stylesheet" href="{% static 'css/base.css' %}">


    {% block css %}

    {% endblock %}

</head>
<body>

<div id='menu'>
    <ul>
        <li><a href='{% url 'home:home' %}'>Home</a></li>
        <li><a href='{% url 'picture:album' %}'>Picture</a></li>
        <li class='has-sub'><a href='{% url 'life:book_list' %}'>Life</a>
            <ul>
                <li><a href='{% url 'life:book_list' %}'>Book</a></li>
                <li><a href='{% url 'life:note_list' %}'>Note</a></li>
                <li><a href='{% url 'life:perception_list' %}'>Perception</a></li>
                <li><a href='{% url 'life:cook_list' %}'>Cook</a></li>
            </ul>
        </li>
        <li class='has-sub'><a href='{% url 'article:article' %}'>Article</a>
            <ul>
                <li class='has-sub'><a href="#">Category</a>
                    <ul>
                        {% for category in category_list %}
                            <li><a href='{% url 'article:category' category.id %}'>{{ category.name }}</a></li>
                        {% endfor %}

                    </ul>
                </li>
                <li class='has-sub'><a href="#">Tag</a>
                    <ul>
                        {% for tag in tag_list %}
                            <li><a href="{% url 'article:tag' tag.id %}">{{ tag.name }}</a></li>
                        {% endfor %}

                    </ul>
                </li>


            </ul>
        </li>

        <li class='has-sub'><a href='{% url 'article:article' %}'>Archive</a>
            <ul>
                {% for year, months in date_merge.items %}

                    <li class='has-sub'><a href="{% url 'article:archive' year 0 %}">{{ year }}年</a>
                        <ul>
                            {% for month in months %}
                                <li><a href="{% url 'article:archive' year month %}">{{ month }} 月</a></li>
                            {% endfor %}
                        </ul>
                    </li>



                {% endfor %}
            </ul>
        </li>

        <li class='has-sub'><a href='{% url 'travel:travel' %}'>Travel</a>
            <ul>
                {% for province in province_list %}
                    <li class='has-sub'><a href='{% url 'travel:province' province.id %}'>{{ province.name }}</a>

                        <ul>
                            {% for city in province.city %}
                                <li><a href='{% url 'travel:city' province.id city.id %}'>{{ city.name }}</a></li>

                            {% endfor %}

                        </ul>


                    </li>

                {% endfor %}

            </ul>
        </li>


        <li><a href='{% url 'home:me' %}'>About me</a></li>
        <li><a href='/admin/'>Manager</a></li>
        <li><a href='https://github.com/blackmonkey121'>git</a></li>
        <li><a href="{% url 'rss' %}">RSS</a></li>
    </ul>
</div>

{% block main %}

{% endblock %}

<div id="background"></div>

<script src="{% static '/js/jquery.min.js' %}"></script>
<script src="{% static '/js/navbar.js' %}"></script>

{% block js %}

{% endblock %}

</body>
</html>

MySpace/apps/home/templates/home.html
{% extends 'base.html' %}

{% block title %}
Monkey的个人站点
{% endblock %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static '/css/home.css' %}">

    <!-- Carousel -->
    <link rel="stylesheet" href="{% static '/css/slick.css' %}">
    <link rel="stylesheet" href="{% static '/css/index.css' %}">
    <link rel="stylesheet" href="{% static '/css/jquery.fullPage.css' %}">
    <!-- icon -->
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">

{% endblock %}

{% block main %}

<div id="index_main" class="index_main">
    <!--导航-->
    <div class="section section1">
        <div class="index_banner">
            <div class="item">
                <div class="items scaleBg" style="background-image: url('{% static '/img/banner1.jpg' %}');"></div>
                <div class="inner">
                    <div class="block_txt">
                        <h4>With Dream, Focus On Life!</h4>
                        <h2><a href="{% url 'picture:album' %}">Picture:</a> 怀揣<span>梦想</span> | 专注 <span> 生活</span></h2>
                        <h3>
                            <div style="text-align:center;margin:50px 0; font:normal 14px/24px 'MicroSoft YaHei';">
                                <p>欢迎来到我的个人站点，我是 <a href="{% url 'home:me' %}">Clark·Monkey</a></p>
                            </div>
                        </h3>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="items scaleBg" style="background-image: url('{% static '/img/banner2.jpg' %}');"></div>
                <div class="inner">
                    <div class="block_txt">
                        <h4> Goodliness,to be continued</h4>
                        <h2><a href="{% url 'life:life' %}">Life:</a> 让<span>美好持续</span>发生</h2>
                        <h3>保持微笑，保持热泪盈眶的真实～</h3>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="items scaleBg" style="background-image: url('{% static '/img/banner3.jpg' %}');"></div>
                <div class="inner">
                    <div class="block_txt">
                        <h4>Do one thing and do it well！</h4>
                        <h2><a href="{% url 'article:article' %}"> Technology：</a>每次<span>只做一件事</span>把它做到极致。</h2>
                        <h3>——最不务正业的Coder.</h3>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="items scaleBg" style="background-image: url('{% static '/img/banner4.jpg' %}');"></div>
                <div class="inner">
                    <div class="block_txt">
                        <h4>Life is a journey, enjoy every encounter and parting.</h4>
                        <h2><a href="{% url 'travel:travel' %}">Travel:</a> 不知风云 <span> 起落</span> ｜ 只见 <span>行色匆匆</span></h2>
                        <h3>一直在路上</h3>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="items scaleBg" style="background-image: url('{% static '/img/banner5.jpg' %}');"></div>
                <div class="inner">
                    <div class="block_txt">
                        <h4>About Me</h4>
                        <h2><a href="{% url 'home:me' %}">About Me:</a> 关于 <span>我</span></h2>
                        <h3>工作、学习、生活、个人自述</h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="left slick_txt">
            <div class="prev slick_arrow"></div>
        </div>
        <div class="right slick_txt">
            <div class="next slick_arrow"></div>
        </div>
        <div class="number">
            <div class="inner clearfix">
                <span class="active">相册</span>
                <span>生活</span>
                <span>技术</span>
                <span>足迹</span>
                <span>关于我</span>
            </div>
        </div>
    </div>

    <div class="section section2">
        <div id="home-picture" class="clearfix">

            <div class="desc">
                <br>
                这些多是一些好友和同事的照片，也有一部分是旅程中拍下的风景...
                <br>
                它们有些配有说明文字，我希望通过这些来记录生活中那些有熟悉的面孔和有趣的灵魂...
                <br>时间太匆匆，
                我们即是在遇见，也是在走散...
                <br>
                无论庆幸或遗憾，总之结局总是美好的，无论如何感谢经历...
            </div>

            <a style="text-decoration:none;" href="{% url 'picture:album' %}"><span id="picture-btn" class="page-btn">相册</span></a>

            <div id="picture-area" class="clearfix">

                {% for album in album_list %}
                    <div class="img">
                        <a href="{% url 'picture:album_detail' album.id %}">
                            <img src="/media/{{ album.cover }}" alt="">
                        </a>
                    </div>
                {% endfor %}

            </div>

        </div>

    </div>

    <div class="section section3">
        <div id="home-article" class="clearfix">
            <a style="text-decoration:none;" href="{% url 'article:article' %}">
                <span id="article-btn" class="page-btn">博文</span>
            </a>
            <div class="article-block hot">
                <div class="block-name">最热文章</div>
                <ul>
                    {% for article in article_hot %}
                        <li><a href="{% url 'article:detail' article.id %}">{{ article.title | truncatechars:'16' }}1</a></li>
                    {% endfor %}

                </ul>
            </div>
            <div class="article-block new">
                <div class="block-name">最新文章</div>

                <ul>
                    {% for article in article_new %}
                        <li><a href="{% url 'article:detail' article.id %}">{{ article.title | truncatechars:'16' }}</a></li>
                    {% endfor %}

                </ul>

            </div>
            <div class="article-block tag">
                <div class="block-name">标签</div>
                <ul>
                    {% for tag in tag_list %}
                        <li class="float-l"><span><i class="fa fa-tag" aria-hidden="true"></i></span><a href="{% url 'article:tag' tag.id %}"> {{ tag.name | truncatechars:'16' }}</a></li>
                    {% endfor %}

                </ul>
            </div>

        </div>
    </div>

    <div class="section section4">
        <div id="home-life">
            <span class="page-btn"><a style="text-decoration:none;" href="{% url 'life:life' %}">生活</a></span>
            <div class="desc">
                无论发生什么，世界还是那个样子——时光如水，从容依旧。 从不因为任何人或事而稍做停歇......
                <br>
                拼命的追逐着，不停的忙碌着。想来，这世间有许多人与我一样，踽踽独行于红尘巷陌。
                <br>
                <br>
                保持乐观积极的态度，抽时间 <span><a href="#">读一读书</a></span>，也给疲惫的心灵放个假。
                <br>
                健康是最宝贵的财富，因此要坚持 <span><a href="#">运动</a></span>。
                <br>
                一定早睡和按时吃饭，最好自己动手，不要给不吃饭找一堆幼稚的理由～<span><a href="#">享受烹饪的快乐</a>～</span>
                <br>
                <span><a href="#">编程</a></span>不仅仅只是工作，而是 <span><a href="">兴趣和爱好</a></span>，它可以让我专注于某一点～我很享受这个过程～
                <br>
                不要将糟糕的事情持续太久 <span><a href="#">Do At Once!</a></span>，做事要专注并且追求高质高效，不要那些没有意义的事情。

            </div>


        </div>
    </div>

    <div class="section section5">

        <a style="text-decoration:none;" href="{% url 'travel:travel' %}"><span class="page-btn">足迹</span></a>
        <ul>

        </ul>
        <div id="home-me">

        </div>
    </div>

</div>

{% endblock %}


{% block js %}
    <script src="{% static '/js/carousel/jquery.fullPage.min.js' %}"></script>
<script src="{% static '/js/carousel/index_slick.js' %}"></script>
<script src="{% static '/js/carousel/index.js' %}"></script>

{% endblock %}

MySpace/apps/home/templates/me.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    About Me :Clark Monkey
{% endblock %}

{% block main %}

    <div id="container">
    <h1 style="text-align: center; color: white; font-size: 42px">页面升级维护中...</h1>
    </div>
{% endblock %}